// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkL5vqQP0xCmg-ZOeemXRWlXi6_acadc',
    appId: '1:163159469770:web:5b156cfe93d4ba8caf4e33',
    messagingSenderId: '163159469770',
    projectId: 'find-mosque-be562',
    authDomain: 'find-mosque-be562.firebaseapp.com',
    storageBucket: 'find-mosque-be562.firebasestorage.app',
    measurementId: 'G-5RP1J8Y5H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByoDg9YKHec3uW3GWtvGjryJODdUvW9ks',
    appId: '1:163159469770:android:02e79a39744a1024af4e33',
    messagingSenderId: '163159469770',
    projectId: 'find-mosque-be562',
    storageBucket: 'find-mosque-be562.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6NI-QnKRr7gWLjQaH1bvmc5jUqmUK8A0',
    appId: '1:163159469770:ios:24e6975113b53ee7af4e33',
    messagingSenderId: '163159469770',
    projectId: 'find-mosque-be562',
    storageBucket: 'find-mosque-be562.firebasestorage.app',
    iosBundleId: 'com.example.findMasjid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6NI-QnKRr7gWLjQaH1bvmc5jUqmUK8A0',
    appId: '1:163159469770:ios:24e6975113b53ee7af4e33',
    messagingSenderId: '163159469770',
    projectId: 'find-mosque-be562',
    storageBucket: 'find-mosque-be562.firebasestorage.app',
    iosBundleId: 'com.example.findMasjid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkL5vqQP0xCmg-ZOeemXRWlXi6_acadc',
    appId: '1:163159469770:web:034d172173b89903af4e33',
    messagingSenderId: '163159469770',
    projectId: 'find-mosque-be562',
    authDomain: 'find-mosque-be562.firebaseapp.com',
    storageBucket: 'find-mosque-be562.firebasestorage.app',
    measurementId: 'G-Q6ZRQ7857S',
  );
}
